### ISSUE TITLE
How to use PermanentPotionTrait

### ISSUE THREAD

**Issue by ninmore** [tobiyas/RacesAndClasses#4]
So I have a configuration that uses PermanentPotionTrait and this was to allow certain races to have the ability to have for example resistance in a Biome. But when they leave the biome the trait used to disable and remove it self but in 1.9 the trait is now infinite once activated, once you have left the biome.

Here is the configuration used:
![notepad _2016-03-13_18-25-34](https://cloud.githubusercontent.com/assets/1499355/13730499/04eb39f8-e949-11e5-873b-129117210e8d.png)

Unformatted text:
`Ramallah:
  config:
    racetag: '[Ramallah]'
    healthbonus: 2
    manabonus: 100
    guislot: -1
  traits:
    PermanentPotionTrait:
      amplifier: 0
      type: 11
      removeParticles: true
      biomes: DESERT,MESA,MESA_PLATEAU,SAVANNA`

**Comment by ninmore** [comment]
There is also this in the latest version of Spigot:
[Server thread/WARN]: [RacesAndClasses] Error in Runnable 'ManaXPBarRunner' in plugin 'RacesAndClasses'
java.lang.NullPointerException
	at de.tobiyas.racesandclasses.playermanagement.spellmanagement.mana.ManaXPBarRunner.runIntern(ManaXPBarRunner.java:31) ~[RacesAndClasses.jar:?]
	at de.tobiyas.util.RaC.schedule.DebugBukkitRunnable.run(DebugBukkitRunnable.java:44) [RacesAndClasses.jar:?]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:71) [spigot.jar:git-Spigot-6f291ea-55a8535]
	at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-6f291ea-55a8535]
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:729) [spigot.jar:git-Spigot-6f291ea-55a8535]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-6f291ea-55a8535]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot.jar:git-Spigot-6f291ea-55a8535]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot.jar:git-Spigot-6f291ea-55a8535]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_71]

**Comment by tobiyas** [comment]
The second error is due to the latest spigot patches.
It is already fixed with the new Saving system.
For temporarly compat, please open up the plugin.yml in the RacesAndClasses.jar and add the line 'database: true'.

**Comment by ninmore** [comment]
Cheers man o/
